---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Set system timezone
  timezone:
    name: "{{ system_timezone }}"

- name: Ensure chrony is running
  service:
    name: chrony
    state: started
    enabled: yes

- name: Enable unattended security upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
